CREATE TABLE `Mood` (
    `id`    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `label`    TEXT NOT NULL
);

CREATE TABLE `Entry` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`concept`	TEXT NOT NULL,
	`entry`	TEXT NOT NULL,
	`date`	INTEGER NOT NULL,
	`moodId`	INTEGER NOT NULL,
     FOREIGN KEY (moodId) REFERENCES Mood(id)
);

SELECT * FROM Entry